### ISSUE TITLE
Data preprocess

### ISSUE THREAD

**Issue by det-tu** [Kaiseem/DAR-UNet#1]
Hi, i wonder in step1 of data processing, how to convert multiple 3d nii files to npy? Is there any requirements? Or can you please release the code of data processing?

Thanks!

**Comment by Kaiseem** [comment]
Hi, for your question, you can load the array through simpleITK library from 3D nii files and save them as npy, e.g., np.save.

Meanwhile, I have detailed all the necessary and general steps to prepare the datasets, similar with [TransUNet](https://github.com/Beckschen/TransUNet/tree/main/datasets), you can also refer to the paper for more detials, e.g., specific spacing for each datasets. And there is no special requirement here to preprocess them.

**Comment by det-tu** [comment]
Thanks for your answer! For target image in CrossModa, the labels are lacked so can't generate label.npy, how to complete the steps in data preprocessing?

**Comment by Kaiseem** [comment]
You are right about it, for the target domain, the annotation is not accessible. So you have to generate the prediction on the target domain with the trained segmentor, and then evaluate your method by submitting the prediction to the official website of CrossMoDa. I don't have the annotation too, so I got the results by submitting the predictions.
