### ISSUE TITLE
关于指标复现问题

### ISSUE THREAD

**Issue by amateurj1** [Kaiseem/DAR-UNet#10]
作者，您好！您的文章思路独特，我使用您的代码和公开的数据https://drive.google.com/file/d/1s3IYf69P1WJBBH5YTFSXwoi7LT9gQUS3/view进行了分割实验，发现指标与您论文中的数据有所差距，特此来请教您！

实验环境为：
1.3090 24G
2.python==3.7.13
3.torch==1.8.0+cu111

实验一：我利用您上面谷歌网盘的数据（腹腔多器官）直接进行第二阶段的分割训练，以下是我的修改过的参数设置。
parser.add_argument('--train_dataroot', type=str, default='datasets/source2target_training_npy_multi_style')
parser.add_argument('--val_dataroot', type=str, default='datasets/target_test_npy')
parser.add_argument('--num_classes', type=int, default=5)
其他参数按照您的默认参数，并且和您论文里的参数进行了对照，是一致的。其中，source2target_training_npy_multi_style和target_test_npy是您提供的数据。我运行了stage_2_seg_train.py进行训练，发现dice和您论文中的91.25有较大的差距。
以下是训练过程中一些loss和dice score的曲线。
![image](https://github.com/Kaiseem/DAR-UNet/assets/48282805/7c8a520d-7a50-4d90-b8f8-3cef6aac9375)

实验二：我下载了您提供的风格迁移权重enc_0040.pt，利用stage_1.5_i2i_inference.py进行source向target的风格迁移后再进行第二阶段的分割训练，发现dice差距就更大了。
![image](https://github.com/Kaiseem/DAR-UNet/assets/48282805/699f171e-0fc7-4fe9-a273-2d47b0f4f22b)

寻求作者大大的帮助，十分感谢！

**Comment by Kaiseem** [comment]
你好，为了可复现性，我没有用target_test_npy进行最终测试，而是用最后一个epoch上的checkpoint，在原图上进行测试，相关测试代码和训练好的checkpoints：
https://pan.baidu.com/s/1wXDjC_zJ3B7G3buhAXgVJg?pwd=19i0

原始数据集（以防需要）：
https://pan.baidu.com/s/14b-ARlbZ7hnG6aO-fil9AA?pwd=picg
