### ISSUE TITLE
pretrained models or psudo data for CrossModa 

### ISSUE THREAD

**Issue by SumayyaInayat** [Kaiseem/DAR-UNet#13]
Hi Kaiseem,
Hope you are doing good.
As you have provided the preprocessed abdominal dataset, like wise can you please provide the crossmoda dataset or share the pretrained models on CrossModa.
Actually I am working on the same dataset for my MS thesis, that's why........your work has already helped me a lot.
Thanks!

**Comment by Kaiseem** [comment]
Hi,

I shared the checkpoints and corresponding inference code here https://drive.google.com/file/d/121fkCuvG9ie_447IX-RqBcE49BCwfjGa/view?usp=sharing

To initiate the validation phase, please ensure that you download the original nii.gz files and place them in the 'datasets/target_validation' directory. This step is crucial for running the validation process accurately.

I would like to highlight that the validation dataset only contains the data without labels. Therefore, I kindly request that you upload the validation results to the designated server. This will enable you to obtain quantitative results based on the validation outcomes.

Furthermore, the testing dataset is not accessible, and it is required to upload an executable Docker container to run on the official server. However, this channel may have been closed.

Wish the msg helps

**Comment by SumayyaInayat** [comment]
Thank you so much KaIseem for helping.
I think you have shared the pretrained segmenter weights, but I actually want the GAN weights, Image to Image translation network weights.
Your work states that two type of domain shift exists inter domain and intra domain, and this is a very strong point specially incase of medical images, as far as I have understood.
That is why I want to compare the images generated from simple CUT and your I-2-I translation network but using some other segmenter.
I hope my point is clear.
Thanks!

**Comment by Kaiseem** [comment]
Sure, https://drive.google.com/file/d/1nhYc2-HzvayV5-4VlKc8_bD4miwWCdWl/view?usp=sharing

good luck :)

**Comment by SumayyaInayat** [comment]
Thanks KaIseem!!!
