### ISSUE TITLE
关于I2I之后的分割模型问题

### ISSUE THREAD

**Issue by qujunda123** [Kaiseem/DAR-UNet#15]
非常感谢您这项出色的工作，在您的帮助之下，我已经能生成比较好的图像。但是将生成的图像和标记输入到模型时候，我发现训练和验证（在生成的图像上验证）的Dice只能达到0.8。再有标记监督下仅能达到0.8，应该是在设置方向出现问题？想请问您模型的训练和验证性能如何呢？
   分割模型是可以工作的，我发现了一个奇怪现象，当我用生成的图像训练时候，学习率已经达到1e-4了，模型才能训练下去，但有时候Dice loss为1，一直维持不变，似乎仍是学习率过大，但感觉这个不符合常规，应为学习率已经很小了。不知道您是否有什么建议呢？非常感谢。

**Comment by Kaiseem** [comment]
你好，对于第一个问题，由于时间久远，我忘了当时的情况了，但凭经验来说，你可以用相同的参数拿original图像的训练和验证集训练一次，看看DICE大小如何。如果这个dice和0.8差距大，说明transfer的网络训练的不好，因为不能靠人肉眼的直觉判断图像是否生成的好，考虑到GAN会隐写术的情况；如果这个差距小，那说明transfer网络训练的不错，是数据集的training和test的distributional gap引起的，这个没办法。

对于第二个问题，这个是有可能的，DICE的loss并不稳定，但效果好；ce loss稳定但效果不一定好。综上，你可以尝试调小dice loss，并且调大cross entropy loss，确保收敛和训练稳定性

**Comment by qujunda123** [comment]
非常感谢您的回答，我现在就直接使用original图像训练尝试一下！

**Comment by qujunda123** [comment]
您好，我还有一个小问题想请教。在迁移分割模型时候，可以使用目标域的图像用来验证模型用来调整参数么 ？
 我用生成的图像和标签可以用来训练模型 ，但是验证调参用哪个指标呢？可以使用目标域标签过的图像和标记调呢？这样做是否符合无监督领域自适应的常规做法呢？验证集用了目标域调参还能说无监督么？
万分感谢

**Comment by Kaiseem** [comment]
你好，实验环境中使用测试集（目标域图像）来调整模型以达到最优结果是比较常见的，你可以直接用DICE score、IoU score。但你需要做比较详尽的sensitive study以证明你的方法对于超参数不敏感，用来说明你的方法对于超参数的鲁棒性，还有就是固定连续seed求平均结果（一般3次或者5次平均）也是被鼓励的（例如DaFormer取了3次结果平均），以证明随机性的不敏感。以上，作为科研实验才比较详尽

**Comment by qujunda123** [comment]
非常感谢您。我现在使用I2I的数据训练分割模型，同时使用I2I的数据和有标记的目标域图像进行验证。验证调参后目标域的测试机进行测试从而确定模型在实际目标域的性能。请问您这样的设置尤其是验证集有目标域标签是被允许的么？符合无监督领域自适应的无监督常规设置么？

**Comment by Kaiseem** [comment]
从最严格的角度来说这相当于利用了目标域的label进行early stop，属于作弊，但是目前来说，大部分的文章都用了这个方法，所以你也可以采用，这是一种科研路径依赖，不用太纠结，例如 DaFormer之前所有的方法里90%基本上都是保存了测试集上最优的模型；另外还有一种思路是缓慢降低学习率直至零（或者梯度下降，比如这篇文章或者resnet的原始文字），然后用最后保存的模型进行测试，这是一种比较好的策略，也被用于很多研究。
