### ISSUE TITLE
关于分割模型训练完成之后的测试程序

### ISSUE THREAD

**Issue by QuintinDong** [Kaiseem/DAR-UNet#17]
作者您好，我使用您的代码完成了分割网络的训练，请问可以分享一下您的测试代码吗？训练完成之后我想看到测试图像的分割结果可视化，如果您能帮助，我将不胜感激！

**Comment by Kaiseem** [comment]
https://pan.baidu.com/s/1wXDjC_zJ3B7G3buhAXgVJg?pwd=19i0   
这里有测试集和测试代码

**Comment by QuintinDong** [comment]
> https://pan.baidu.com/s/1wXDjC_zJ3B7G3buhAXgVJg?pwd=19i0 这里有测试集和测试代码
收到，谢谢您的分享！
