### ISSUE TITLE
stage_2_seg_train.py运行

### ISSUE THREAD

**Issue by LaBaicai02** [Kaiseem/DAR-UNet#19]
python stage_2_seg_train.py --name experiment --train_dataroot SOURCE2TARGET_PATH --val_dataroot TARGET_VAL_PATH --num_classes NUM_CLASS --epoch_max 100
![image](https://github.com/Kaiseem/DAR-UNet/assets/93875698/a2acee9e-a8a1-4b6f-a307-b963f967ac48)
 您好请问--train_dataroot和--val_dataroot分别选哪两个数据集呢

**Comment by Steven-ZN** [comment]
同问

**Comment by Kaiseem** [comment]
--train_dataroot source2target_trainin_npy_multi_style --val_dataroot target_test_npy
