### ISSUE TITLE
关于最后测试结果

### ISSUE THREAD

**Issue by QuintinDong** [Kaiseem/DAR-UNet#20]
打扰作者，我按您的训练策略，由于显存原因，在分割网络dataloader中将图像和标签resize到128，并将batchsize改为1，其余没有任何改动，训练100eopch,然后最终的测试结果为Dice per class:  0.8173324 0.0039876397 0.24330574 0.55620456 Overall Dice:  0.4052075743675232
ASD per class:  2.367802277804098 26.726564945072344 7.202804602593032 4.151737284935796 Overall ASD:  10.112227277601319，可以看出第二类和第三类分割结果异常的差，请问您觉得这是什么导致的呢？

**Comment by Kaiseem** [comment]
如果我没理解错的话，你是把图像和标签缩小了4倍训练？你有在测试的时候进行同样的缩小吗？还有就是batch norm/group nom对batch size敏感，这个影响挺大

**Comment by LaBaicai02** [comment]
> 打扰作者，我按您的训练策略，由于显存原因，在分割网络dataloader中将图像和标签resize到128，并将batchsize改为1，其余没有任何改动，训练100eopch,然后最终的测试结果为Dice per class: 0.8173324 0.0039876397 0.24330574 0.55620456 Overall Dice: 0.4052075743675232 ASD per class: 2.367802277804098 26.726564945072344 7.202804602593032 4.151737284935796 Overall ASD: 10.112227277601319，可以看出第二类和第三类分割结果异常的差，请问您觉得这是什么导致的呢？

hello,我想问下evaluation的代码在哪里啊
