### ISSUE TITLE
Normalization Range [0,1] or [-1,1]

### ISSUE THREAD

**Issue by YoungYan-0** [Kaiseem/DAR-UNet#4]
Dear Dr. Yao,

I noticed that in the paper it says that "We perform min-max normalization to rescale the images intensity to the the range [−1,1]".

However, in the README.md inside the datasets folder, it says that "Normalize each 3D images to [0, 1]".

Which range should I use or does it matter?

Best Regards,

Yucheng

**Comment by Kaiseem** [comment]
Hi,

Please follow the READMI.md to normalize the 3D images to [0, 1], which is the preparation of the datasets. The preprocessing is in the https://github.com/Kaiseem/DAR-UNet/blob/68a5b994374ba66b0bf72225080a39bc5dbd06f3/utils/dataloader3d.py#L81 (rescale the intensity to [-1, 1]), which is consistent to our paper statement.

If you have any other question, pls let me know. :)

**Comment by YoungYan-0** [comment]
Thank you!
