### ISSUE TITLE
预处理数据

### ISSUE THREAD

**Issue by lzy-whut** [Kaiseem/DAR-UNet#6]
您好，我根据您论文里的叙述生成了A_imgs.npy和B_imgs.npy两个文件用于第一阶段的训练，可是训练失败了，您方便提供下您使用的A_imgs.npy和B_imgs.npy两个文件吗？

**Comment by lzy-whut** [comment]
腹腔多器官分割的数据

**Comment by Kaiseem** [comment]
好的，我上传下，稍微有点大，另外之前有个人要了二阶段的数据集和checkpoint 在这https://pan.baidu.com/s/1o1SkmxiXj45IbsIm8F1hgQ?pwd=66vs

**Comment by lzy-whut** [comment]
好的，十分感谢您，第二阶段的数据我已经下载了

**Comment by Kaiseem** [comment]
https://pan.baidu.com/s/148yIuOkix2FlvnSjzv2esg?pwd=6sl1

**Comment by lzy-whut** [comment]
还有几个问题想要请教您
1、论文中有这样一句话” Since CT data include the area from neck to knee while MRI data only contain the abdominal area, we crop the CT images to have the same view with MRI.“ 这个过程是具体怎么操作的呢？
2、第一二阶段所使用的数据在处理上是一样的吗？如果不一样具体体现在哪里呢？

**Comment by lzy-whut** [comment]
还有就是target_training_npy除外的四例测试集MRI数据是否方便上传下？

**Comment by Kaiseem** [comment]
https://pan.baidu.com/s/1r4ZPkv7x1hy_lvFQ9ydOZw?pwd=2ku7 
这个压缩文件里包含了预处理的代码和target的测试集，对于问题1我follow了前人的工作，裁剪了包含GT的slices，针对问题2，理论上是一样的，详情可以见预处理的文件

**Comment by lzy-whut** [comment]
十分感谢！
