### ISSUE TITLE
关于stage one image-to-image translation model 的问题

### ISSUE THREAD

**Issue by Heodel** [Kaiseem/DAR-UNet#8]
作者您好，您的文章思路对我非常具有帮助。

根据您之前的issues，我下载了通过k-means方法生成的不同style的target-like 的图像，对npy文件进行可视化后，发现您生成的效果非常好，因此相对如何更好的生成target-like的图像做一个更深入的研究。因此，我对第一步您训练 image-to-image translation model的过程（stage_1_i2i_train.py）进行了复现，并运行了stage_1.5_i2i_inference.py，然后发现与您已经生成好的图像有一些细节差别。因此，能否分享一下stage_1.5_i2i_inference.py中在腹部数据集上已经预训练好的权重 (代码第十行：parser.add_argument('--ckpt_path', type=str, default='test/i2i_checkpoints/enc_0040.pt')，i2i_checkpoints，source2target与target2source的生成权重文件)？

期待您的回复，万分感谢！

**Comment by Kaiseem** [comment]
你好 ，权重可以在此下载： 

链接：https://pan.baidu.com/s/1RlIih7l9q7DJZpVxBWekKw?pwd=s2q9 
提取码：s2q9

**Comment by Heodel** [comment]
作者您好，十分感谢您在百忙之中的回复。

对于MR->CT域上的转换的生成器预训练，我尝试修改了stage_1_i2i_train中的数据集gan_forward顺序：

```
原始代码（A to B）：trainer.gan_forward(train_data['A_img'], train_data['B_img'])
修改代码（B to A）：trainer.gan_forward(train_data['B_img'], train_data['A_img'])

```

再次感谢您提供的预训练权重，这位将有助于进一步测试。我收到了您提供的enc_0040.pt的文件。请问您一下该文件（enc_0040.pt）是腹部数据集CT->MR（A to B）的转换权重吗？target2source（MR->CT，BtoA）的权重能否进一步提供一下呢？

期待您的回复！

**Comment by Kaiseem** [comment]
你好 不用客气 ，ct-mri和mri-ct的权重应该是同一个

**Comment by Heodel** [comment]
谢谢您的回复，已经收到，谢谢！
