### ISSUE TITLE
关于第二阶段的数据

### ISSUE THREAD

**Issue by amateurj1** [Kaiseem/DAR-UNet#9]
作者您好，想问您要一下第二阶段的数据（腹腔多器官），我已经进行了第一阶段的训练，想要执行stage_1.5_i2i_inference.py 生成图片。在另一个issue里发现分享链接已经过期了。能否麻烦您再分享一下第二阶段的数据以及预处理代码呢？十分感谢您！！

**Comment by Kaiseem** [comment]
Hi，我上传了数据集在这，

链接：https://pan.baidu.com/s/1P5XAl_xW3oV42fefVLaMXQ?pwd=7so5 
提取码：7so5 

此外，image-to-image translation的网络权重
链接：https://pan.baidu.com/s/1RlIih7l9q7DJZpVxBWekKw?pwd=s2q9
提取码：s2q9

**Comment by amateurj1** [comment]
收到！十分感谢！
